### ISSUE TITLE
mec documentation missing most symbols

### ISSUE THREAD

**Issue by jauhl** [goessner/g2#19]
The only documented symbol seems to be `.pol()`. Other symbols, e.g. `.nodfix()`, are not metioned and there's is no overview of what they look like.

**Comment by klawr** [comment]
The wiki is almost up to date now.
I hope this will be sufficient:
https://github.com/goessner/g2/wiki/g2.mec

**Comment by jauhl** [comment]
Please also update https://github.com/goessner/g2/blob/master/docs/api/g2.mec.md which is imho even more important.

**Comment by klawr** [comment]
I see... The problem is not that they are not mentioned... The headline is wrong due to the automatic naming of js2md.
g2.pol() is just the first symbol. as you can see the description is for all symbols at once, since they dont differ in usage:
https://github.com/goessner/g2/blob/master/docs/api/g2.mec.md#g2pol

I will have a look at how to group them sufficiently.

**Comment by klawr** [comment]
I have not found a solution to group them, but this way it is more correct anyway.
Please check if this is okay now: https://github.com/goessner/g2/blob/master/docs/api/g2.mec.md#g2+pol

**Comment by jauhl** [comment]
Looks fine but maybe also break down the example from `pol()` to the corresponding methods.
```js
g2().view({cartesian:true})
    .pol({x:20,y:75})
    .gnd({x:60,y:75})
    .nod({x:100,y:75})
    .dblnod({x:140,y:75})
    .nodfix({x:180,y:75})
    .nodflt({x:220,y:75})
    .origin({x:260,y:75})
```

**Comment by klawr** [comment]
I thought about that, but don't you think that's too much repetition then?

**Comment by jauhl** [comment]
No. Since e.g. `dblnod()` does not depend on `pol()` i don't want to have to search around and look up how it works in other methods. And since 
```js
.gnd({x:60,y:75})
    .nod({x:100,y:75})
    .dblnod({x:140,y:75})
    .nodfix({x:180,y:75})
    .nodflt({x:220,y:75})
    .origin({x:260,y:75})
```
can be excluded from the `pol()` example, it's not much more lines of documentation in total.

**Comment by klawr** [comment]
Changed according to your suggestion:
https://github.com/goessner/g2/blob/master/docs/api/g2.mec.md#g2+pol
