### ISSUE TITLE
pulley2 angle not working 

### ISSUE THREAD

**Issue by jauhl** [goessner/g2#20]
At least `.pulley2()` should support `w` as an argument and does that according to the API reference.
However, after passing a dynamic `w` the orientation of the pulley remains static.

`.pulley2({x:mec.A.x, y:mec.A.y, r:R, w:-phi*l/R})`

Since i can't find any trace of  `w` in the associated methods (`pulley()` and `pulley2()`), this seems to be an oversight...

**Comment by klawr** [comment]
Wiki is not up to date at the moment, but i will get to that as soon as possible.
Fixed in ef184fd4fa9f7dc1af00ec6d36a1f26dde085a88
