### ISSUE TITLE
'grid()' does not work...

### ISSUE THREAD

**Issue by cd** [goessner/g2#4]
... without arguments object for constructor function:

```
g2({}).grid(); // works
g2().grid();   // does not work
```

**Comment by cd** [comment]
after update `grid()` works now, but `pan()` and `zoom()` do not, because `this.state.trf0` does not exist (only `this.state`).

**Comment by goessner** [comment]
.. resolved ..

Am 21.05.2015 um 08:54 schrieb cd:
